In [2]:
!pip install selenium

Requirement already satisfied: selenium in d:\users\kakug\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in d:\users\kakug\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in d:\users\kakug\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in d:\users\kakug\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in d:\users\kakug\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

# QUES 1:-

Write a python program which searches all the product under a particular product from www.amazon.in. The
product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for
guitars.

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get('https://www.amazon.in/')

In [5]:
product=input('Enter the product to be searched: ')

Enter the product to be searched: guitar

# Ques 2:-

In the above question, now scrape the following details of each product listed in first 3 pages of your search
results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then
scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [6]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search.send_keys('Guitar')

In [7]:
search_button=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search_button.click()

In [8]:
product_urls=[]
start=0
end =3
for page in range(start,end):
    url=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in url:
        product_urls.append(i.get_attribute("href"))
    next_button = driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    next_button.click()
    time.sleep(3)

In [9]:
len(product_urls)

166

In [10]:
Brand_name=[]
Name=[]
Price=[]
Return_policy=[]
Expected_delivery=[]
Availability=[]

for url in product_urls:
    driver.get(url)
    time.sleep(2)
    
    try:
        brand=driver.find_element(By.XPATH,'//tr[@class="a-spacing-small po-brand"]/td[2]/span')
        Brand_name.append(brand.text)
    except NoSuchElementException:
        Brand_name.append('-')
        
        
    try:
        name=driver.find_element(By.XPATH,'//h1[@class="a-size-large a-spacing-none"]')
        Name.append(name.text)
    except NoSuchElementException:
        Name.append('-')
        
        
    try:
        price=driver.find_element(By.XPATH,'//span[@class="a-price-whole"]')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('-')
        
    try:
        delivery=driver.find_element(By.XPATH,'//div[@class="a-spacing-base"]/span/span')
        Expected_delivery.append(delivery.text)
    except NoSuchElementException:
        Expected_delivery.append('-')
        
     
    try:
        Return=driver.find_element(By.XPATH,'//*[@id="RETURNS_POLICY"]/span/div[2]/span')
        Return_policy.append(Return.text)
    except NoSuchElementException:
        Return_policy.apend('-')
        
        
    try:
        available=driver.find_element(By.XPATH,'//div[@id="availability"]')
        Availability.append(available.text)
    except NoSuchElementException:
        Availabilty.append('-')

In [13]:
import pandas as pd
data=pd.DataFrame({'Brand':Brand_name,'ReturnExchange':Return_policy,'Price':Price,'Delivery_by':Expected_delivery,'Name of Product':Name,'Availability of product':Availability,'urls':product_urls})
data

,Brand,ReturnExchange,Price,Delivery_by,Name of Product,Availability of product,urls
0,Kadence,7 days Replacement,"₹4,899","Monday, 29 April","Kadence rosewood Guitar Frontier Series, Elect...",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Kadence,7 days Replacement,"₹4,799","Friday, 26 April",Kadence Frontier guitar with Online Guitar lea...,In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kadence,7 days Replacement,"₹9,999","Friday, 26 April",Kadence Slowhand Premium Jumbo Semi Acoustic G...,In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,RICHTONE,7 days Replacement,"₹9,000","Wednesday, 1 May",Richtone B239C Natural Matt JF style cutaway A...,Only 2 left in stock.,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,JUAREZ,7 days Replacement,"₹2,199","Monday, 29 April","Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...",In stock,https://www.amazon.in/Acoustic-Cutaway-RDS-Str...
...,...,...,...,...,...,...,...
161,Tanglewood,7 days Replacement,"₹10,490","Friday, 26 April","Tanglewood Crossroads TWCR O Acoustic Guitar, ...",In stock,https://www.amazon.in/Tanglewood-Crossroads-Ac...
162,Fender,7 days Replacement,"₹1,25,663","Friday, 26 April",Fender Electric Guitar Player Plus Strat HSS M...,Only 1 left in stock.,https://www.amazon.in/Fender-0147322376-Player...
163,Kadence,7 days Replacement,"₹6,799","Monday, 29 April","Kadence 40"" Acoustic Guitar FR77 Spruce Wood w...",In stock,https://www.amazon.in/Kadence-Acoustic-Rosewoo...
164,Schecter,7 days Replacement,"₹84,399","Friday, 26 April",Schecter Tempest Custom Faded Vintage Sunburst...,Only 1 left in stock.,https://www.amazon.in/Schecter-Tempest-Vintage...
165,Radhe Flutes,Non-Returnable,₹399,"Thursday, 25 April",Radhe Flutes | Right Handed C Natural With Vel...,In stock,https://aax-eu.amazon.in/x/c/RAk1EcTS7jU9d49sS...

# Ques 3:-

Write a python program to access the search bar and search button on images.google.com and scrape 10
images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [3]:
#importing library
from bs4 import BeautifulSoup
#Importing requests
import requests
# importing regex
import re

In [42]:
driver=webdriver.Chrome()

In [32]:
driver.get('https://images.google.com/')
driver.maximize_window()

In [17]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search.send_keys('fruits')

In [22]:
search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button')
search_button.click()

In [28]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,500)")
    
img_urls=[]
images=driver.find_elements(By.XPATH,'//img[@class="YQ4gaf"]')
for image in images:
    source=image.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i>10:
        break
    print("Downloading{0} of {1} images".format(i,10))
    response=requests.get(img_urls[i])
    file=open(r"C:\Users\kakug\OneDrive\Desktop\assignment 3"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading0 of 10 images
Downloading1 of 10 images
Downloading2 of 10 images
Downloading3 of 10 images
Downloading4 of 10 images
Downloading5 of 10 images
Downloading6 of 10 images
Downloading7 of 10 images
Downloading8 of 10 images
Downloading9 of 10 images
Downloading10 of 10 images

In [34]:
search_bar=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar.send_keys('cars')

search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button')
search_button.click()

In [35]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,500)")
    
img_urls=[]
images=driver.find_elements(By.XPATH,'//img[@class="YQ4gaf"]')
for image in images:
    source=image.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls.append(source)
            
            
for i in range(len(img_urls)):
    if i>10:
        break
    print("Downloading{0} of {1} images".format(i,10))
    response=requests.get(img_urls[i])
    file=open(r"C:\Users\kakug\OneDrive\Desktop\assignment 3"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading0 of 10 images
Downloading1 of 10 images
Downloading2 of 10 images
Downloading3 of 10 images
Downloading4 of 10 images
Downloading5 of 10 images
Downloading6 of 10 images
Downloading7 of 10 images
Downloading8 of 10 images
Downloading9 of 10 images
Downloading10 of 10 images

# Ques 4:-

Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the
details is missing then replace it by “- “. Save your results in a dataframe and CSV

In [37]:
driver=webdriver.Chrome()
driver.get('https://www.flipkart.com/')
driver.maximize_window()

In [38]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input')
search.send_keys('OnePlus Nord')

In [39]:
search_button=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button')
search_button.click()

In [40]:
product_url = []
#locate the product url
url=driver.find_elements(By.XPATH,'//a[@class="CGtC98"]')
for i in url:
    product_url.append(i.get_attribute("href"))    
    
len(product_url)

24

In [58]:

Brand=[]
name=[]
Colour=[]
RAM=[]
ROM=[]
Primary_Camera=[]
Secondary_Camera=[]
Display=[]
Battery=[]
Price=[]


for url in product_url:
    driver.get(url)
    time.sleep(2)
    
        
    #Scraping brand name of phone 
    try:
        brand_tags = driver.find_element(By.XPATH,'//span[@class="VU-ZEz"]')      
        Brand.append(brand_tags.text.split()[0])
    except NoSuchElementException:
        Brand.append('-')
    #Scraping phone name 
    try:
        name_tags = driver.find_element(By.XPATH,'//div[@class="GNDEQ-"][1]/table[1]/tbody[1]/tr[3]/td[2]')     
        name.append(name_tags.text)
    except NoSuchElementException:
        name.append('-')
    
    #Scraping phone color data
    try:                                          
        color_tags = driver.find_element(By.XPATH,'//div[@class="GNDEQ-"][1]/table[1]/tbody[1]/tr[4]/td[2]')      
        Colour.append(color_tags.text)
    except NoSuchElementException:
        Colour.append('-')
    read_more=driver.find_element(By.XPATH,'//button[@class="QqFHMw _4FgsLt"]')
    read_more.click()    
    
     #Scraping RAM data
    try:
        ram_tags = driver.find_element(By.XPATH,'//div[@class="GNDEQ-"][4]/table/tbody/tr[2]/td[2]')                
        RAM.append(ram_tags.text)
    except NoSuchElementException:
        RAM.append('-')
    
    
    #Scraping ROM data
    try:
        rom_tags = driver.find_element(By.XPATH,'//div[@class="GNDEQ-"][4]/table/tbody/tr[1]/td[2]')        
        ROM.append(rom_tags.text)
    except NoSuchElementException:
        ROM.append('-')
        
    #Scraping Primary camera 
    try:                                                                                    
        pri_tags = driver.find_element(By.XPATH,'//div[@class="cPHDOP col-6-12"]/div/div[2]/ul/li[3]')
        Primary_Camera.append(pri_tags.text)
    except NoSuchElementException:
        Primary_Camera.append('-')
       
    #Scraping Secondary camera 
    try:                                                                                    
        sr_tags = driver.find_element(By.XPATH,'//div[@class="GNDEQ-"][5]/table/tbody/tr[2]/td[2]')
        Secondary_Camera.append(sr_tags.text)
    except NoSuchElementException:
        Secondary_Camera.append('-')
    
    
    #Scraping Display size 
    try:
        disp_tags = driver.find_element(By.XPATH,'//div[@class="cPHDOP col-6-12"][1]/div/div[2]/ul/li[2]')
        Display.append(disp_tags.text)
    except NoSuchElementException:
        Display.append('-')
    
    #Scraping Battery Capacity  
    try:
        batt_tags = driver.find_element(By.XPATH,'//div[@class="cPHDOP col-6-12"]/div/div[2]/ul/li[4]')
        Battery.append(batt_tags.text)
    except NoSuchElementException:
        Battery.append('-')
        
     #Scraping Price 
    try:
        price_tags = driver.find_element(By.XPATH,'//div[@class="UOCQB1"]/div/div[1]')      
        Price.append(price_tags.text)
    except NoSuchElementException:
        Price.append('-')

In [59]:
import pandas as pd
smartphone=pd.DataFrame({"brand_name":Brand[:24],"smartphone_name":name[:24],"product_colour":Colour[:24],"product_RAM":RAM[:24],
                         "product_ROM":ROM[:24],"Primary_Camera":Primary_Camera[:24],"Secondary_Camera":Secondary_Camera[:24],
                         "Display":Display[:24],"Battery_Capacity":Battery[:24],"Phone_Price":Price[:24],"Product_URL":product_url[:24]})

smartphone

,brand_name,smartphone_name,product_colour,product_RAM,product_ROM,Primary_Camera,Secondary_Camera,Display,Battery_Capacity,Phone_Price,Product_URL
0,OnePlus,Nord CE 3 Lite 5G,Pastel Lime,8 GB,256 GB,108MP Rear Camera,Primary Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹19,699",https://www.flipkart.com/oneplus-nord-ce-3-lit...
1,OnePlus,Nord CE 3 Lite 5G,Chromatic Gray,8 GB,256 GB,108MP Rear Camera,Primary Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹19,470",https://www.flipkart.com/oneplus-nord-ce-3-lit...
2,OnePlus,Nord CE 3 Lite 5G,Chromatic Gray,8 GB,128 GB,108MP Rear Camera,Primary Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹17,410",https://www.flipkart.com/oneplus-nord-ce-3-lit...
3,OnePlus,Nord CE 3 Lite 5G,Pastel Lime,8 GB,128 GB,108MP Rear Camera,Primary Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹17,408",https://www.flipkart.com/oneplus-nord-ce-3-lit...
4,OnePlus,Nord CE4,Celadon Marble,8 GB,256 GB,50MP Rear Camera,50MP Rear Camera,17.02 cm (6.7 inch) Display,5500 mAh Battery,"₹26,420",https://www.flipkart.com/oneplus-nord-ce4-cela...
5,OnePlus,Nord CE4,Dark Chrome,8 GB,128 GB,50MP Rear Camera,50MP Rear Camera,17.02 cm (6.7 inch) Display,5500 mAh Battery,"₹24,406",https://www.flipkart.com/oneplus-nord-ce4-dark...
6,OnePlus,Nord CE 2 Lite 5G,Blue Tide,6 GB,128 GB,64MP Rear Camera | 16MP Front Camera,16MP Front Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,"₹16,544",https://www.flipkart.com/oneplus-nord-ce-2-lit...
7,OnePlus,Nord CE4,Dark Chrome,8 GB,256 GB,50MP Rear Camera,50MP Rear Camera,17.02 cm (6.7 inch) Display,5500 mAh Battery,"₹26,717",https://www.flipkart.com/oneplus-nord-ce4-dark...
8,OnePlus,Nord CE4,Celadon Marble,8 GB,128 GB,50MP Rear Camera,50MP Rear Camera,17.02 cm (6.7 inch) Display,5500 mAh Battery,"₹24,539",https://www.flipkart.com/oneplus-nord-ce4-cela...
9,OnePlus,Nord 3 5G,Tempest Gray,16 GB,256 GB,50MP Rear Camera,Primary Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹36,000",https://www.flipkart.com/oneplus-nord-3-5g-tem...
10,OnePlus,Nord 3 5G,Tempest Gray,8 GB,128 GB,50MP Rear Camera,50MP Rear Camera,17.12 cm (6.74 inch) Full HD+ Display,5000 mAh Battery,"₹23,028",https://www.flipkart.com/oneplus-nord-3-5g-tem...
11,OnePlus,Nord 3 5G,Misty Green,16 GB,256 GB,50MP Rear Camera,Primary Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹37,630",https://www.flipkart.com/oneplus-nord-3-5g-mis...
12,OnePlus,Nord 3 5G,Misty Green,8 GB,128 GB,50MP Rear Camera,Primary Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹23,237",https://www.flipkart.com/oneplus-nord-3-5g-mis...
13,OnePlus,Nord CE 2 Lite 5G,Black Dusk,6 GB,128 GB,64MP Rear Camera | 16MP Front Camera,16MP Front Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,"₹16,399",https://www.flipkart.com/oneplus-nord-ce-2-lit...
14,OnePlus,Nord 2T 5G,Jade Fog,8 GB,128 GB,50MP Rear Camera | 32MP Front Camera,32MP Front Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹27,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
15,OnePlus,Nord CE3 5G,Grey Shimmer,8 GB,128 GB,50MP Rear Camera,Primary Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹21,499",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
16,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,50MP Rear Camera,-,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
17,OnePlus,Nord CE3 5G,Aqua Surge,8 GB,128 GB,50MP Rear Camera | 16MP Front Camera,16MP Front Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹21,982",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
18,OnePlus,Nord CE3 5G,Grey Shimmer,12 GB,256 GB,50MP Rear Camera,Primary Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹28,499",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
19,OnePlus,Nord CE3 5G,Aqua Surge,12 GB,256 GB,50MP Rear Camera,Primary Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹28,499",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
20,OnePlus,Nord 2T 5G,Jade Fog,8 GB,128 GB,50MP Rear Camera,-,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹26,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
21,OnePlus,Nord 2T 5G,Jade Fog,12 GB,256 GB,50MP Rear Camera,-,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹33,990",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
22,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,50MP Rear Camera | 32MP Front Camera,32MP Front Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹28,989",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
23,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,50MP Rear Camera,-,17.02 cm (6.7 inch) Display,4500 mAh Battery,"₹26,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...

# Ques 5:-

Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [4]:
#user input
city = input('Enter City name that has to be searched : ')
city

Enter City name that has to be searched : Bahadurgarh

'Bahadurgarh'

In [5]:
#connect to the driver
driver = webdriver.Chrome()
driver.get('https://www.google.co.in/maps')
time.sleep(1)

#Sending keyword for seach bar and search button
search_bar = driver.find_element(By.XPATH,"//input[@id='searchboxinput']")                       
search_bar.clear()                                                             
time.sleep(1)
search_bar.send_keys(city)   

#click search button
search_btn = driver.find_element(By.XPATH,"//button[@id='searchbox-searchbutton']")              
search_btn.click()                                                             
time.sleep(1)

try:
    url_str = driver.current_url
    print("URL Extracted: ", url_str)
    latitude_longitude = re.findall(r'@(.*),',url_str)
    #print(latitude_longitude)
    if len(latitude_longitude):
        lat_lng_list = latitude_longitude[0].split(",")
        if len(lat_lng_list)>=2:
            latitude = lat_lng_list[0]
            longitude = lat_lng_list[1]
        print("Latitude = {}, Longitude = {}".format(latitude, longitude))

except Exception as e:
        print("Error: ", str(e))

URL Extracted:  https://www.google.co.in/maps/search/Bahadurgarh/@30.3300608,76.8400162,15z?entry=ttu
Latitude = 30.3300608, Longitude = 76.8400162

# Ques 6:-

Write a program to scrap all the available details of best gaming laptops from digit.in.

In [16]:
driver=webdriver.Chrome()

In [17]:
driver.get('https://www.digit.in/')

In [18]:
driver.maximize_window()

In [20]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/div/div/button')
search.click()

In [21]:
top10=driver.find_element(By.XPATH,'/html/body/div[4]/div/ul/li[4]')
top10.click()

In [22]:
ai_gaming=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div/div[2]/div[1]/div[3]/div[11]')
ai_gaming.click()

In [23]:
product_url = []
#locate the product url
url=driver.find_elements(By.XPATH,'//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
for i in url:
    product_url.append(i.get_attribute("href"))    
    
len(product_url)

7

In [25]:
name=[]
operating_system=[]
display_size=[]
processor=[]

for url in product_url:
    driver.get(url)
    time.sleep(2)
    
    # scarping laptop name:
    
    try:
        Name=driver.find_element(By.XPATH,'//div[@class="woo_bl_title flowhidden mb10"]/h1')
        name.append(Name.text)
    except NoSuchElementException:
        name.append('-')
        
    # scraping operating system:
    try:
        os=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[1]/div/p[2]')
        operating_system.append(os.text)
    except NoSuchElementException:
        operating_system.append('-')
        
    # scraping display size:
    try:
        display=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[2]/div/p[2]')
        display_size.append(display.text)
    except NoSuchElementException:
        display_size.append('-')
        
     # Scraping processor:
    try:
        pro=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[3]/div/p[2]')
        processor.append(pro.text)
    except NoSuchElementException:
        processor.append('-')

In [26]:
import pandas as pd
df=pd.DataFrame({'Name':name,'Operating System':operating_system,'Display size':display_size,'Processor':processor})
df

,Name,Operating System,Display size,Processor
0,Asus ROG Zephyrus G14 GA402XZ-N2019WS,Windows 11 Home,14,"7th Gen, AMD Ryzen 9 7940HS"
1,MSI Pulse 17 AI C1VGKG,Windows 11 Home,17,Intel Core Ultra 9
2,Acer Nitro 16 AN16-41 | Ryzen 7 7840HS | RTX 4...,Windows 11 Home,16,AMD Ryzen 7-7840HS
3,MSI Bravo 15 C7VFKP,Windows 11 Home,15.6,AMD Ryzen 7-7000HS
4,ASUS TUF Gaming A16 Advantage Edition (2023) F...,Windows 11 Home,16,AMD Ryzen 9-7940HS
5,HP OMEN Gaming Laptop 16 XD0007ax,Windows 11 Home,16.1,AMD Ryzen 7-7840HS
6,Dell New G15 5535,Windows 11 Home,15.6,AMD Ryzen 5-7640HS

# Ques 7:-

Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped:
“Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [4]:
driver=webdriver.Chrome()

In [5]:
driver.get("https://www.forbes.com/?sh=fded0b72254c")

In [6]:
driver.maximize_window()

In [7]:
button=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div')
button.click()

In [8]:
billion=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[1]')
billion.click()

In [10]:
desired=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/header/div[1]/div[1]/div[2]/ul/li[2]/div[2]/div[3]/ul/li[1]')
desired.click()

In [17]:
rank=[]
name=[]
net_worth=[]
age=[]
country=[]
source=[]
industry=[]

# scraping rank:
try:
    Rank=driver.find_elements(By.XPATH,'//div[@role="cell"][1]')
    for i in Rank:
        rank.append(i.text)
        
except:
    rank.append('-')

# scraping name:    
try:
    Name=driver.find_elements(By.XPATH,'//div[@role="cell"][2]')
    for i in Name:
        name.append(i.text)
except:
    name.append('-')
    
# scraping net_worth:
try:
    worth=driver.find_elements(By.XPATH,'//div[@role="cell"][3]')
    for i in worth:
        net_worth.append(i.text)
except:
    net_worth.append('-')
    
# scraping age:
try:
    Age=driver.find_elements(By.XPATH,'//div[@role="cell"][4]')
    for i in Age:
        age.append(i.text)
except:
    age.append('-')
    
# scraping country:
try:
    Country=driver.find_elements(By.XPATH,'//div[@role="cell"][5]')
    for i in Country:
        country.append(i.text)
except:
    country.append('-')
    
# scraping source:
try:
    Source=driver.find_elements(By.XPATH,'//div[@role="cell"][6]')
    for i in Source:
        source.append(i.text)
except:
    source.append('-')

# scraping Industry:
try:
    Industry=driver.find_elements(By.XPATH,'//div[@role="cell"][7]')
    for i in Industry:
        industry.append(i.text)
except:
    industry.append('-')

In [18]:
print(len(rank),len(name),len(net_worth),len(age),len(country),len(source),len(industry))

200 200 200 200 200 200 200

In [19]:
import pandas as pd
df=pd.DataFrame({'Rank':rank,'name':name,'Net worth':net_worth,'age':age,'country':country,'source':source,'Industry':industry})
df

,Rank,name,Net worth,age,country,source,Industry
0,1.,Bernard Arnault & family,$233 B,75,France,LVMH,Fashion & Retail
1,2.,Elon Musk,$195 B,52,United States,"Tesla, SpaceX",Automotive
2,3.,Jeff Bezos,$194 B,60,United States,Amazon,Technology
3,4.,Mark Zuckerberg,$177 B,39,United States,Facebook,Technology
4,5.,Larry Ellison,$141 B,79,United States,Oracle,Technology
...,...,...,...,...,...,...,...
195,195.,Lei Jun,$10.9 B,54,China,Smartphones,Technology
196,195.,Georg Schaeffler,$10.9 B,59,Germany,Auto parts,Automotive
197,195.,Marcel Herrmann Telles & family,$10.9 B,74,Brazil,Beer,Food & Beverage
198,199.,David Velez & family,$10.8 B,42,Colombia,Fintech,Finance & Investments
199,200.,Suleiman Kerimov & family,$10.7 B,58,Russia,Gold,Finance & Investments

# Ques 8:-

Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted
from any YouTube Video

In [20]:
driver=webdriver.Chrome()

In [21]:
driver.get('https://www.youtube.com/')

In [22]:
driver.maximize_window()

In [23]:
search=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/form/div[1]/div[1]/input')
search.send_keys('hanuman chalisa')

In [25]:
button=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/button/yt-icon/yt-icon-shape/icon-shape/div')
button.click()

In [28]:
video=driver.find_element(By.XPATH,'/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[3]/div[1]/div/div[1]/div/h3/a/yt-formatted-string')
video.click()

In [29]:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,10000)")

In [30]:
comments=[]
upvote=[]
time=[]

try:
    comment=driver.find_elements(By.XPATH,'//*[@id="content-text"]')
    for i in comment:
        comments.append(i.text)
except:
    comments.append('-')   

try:
    vote=driver.find_elements(By.XPATH,'//*[@id="vote-count-middle"]')
    for i in vote:
        upvote.append(i.text)
except:
    upvote.append('-')

try:
    Time=driver.find_elements(By.XPATH,'//*[@id="published-time-text"]/a')
    for i in Time:
        time.append(i.text)
except:
    time.append('-')

In [31]:
import pandas as pd
df=pd.DataFrame({'comment':comments,'comment upvote':upvote,'posted time':time})
df

,comment,comment upvote,posted time
0,आज 23 अप्रैल हनुमान जन्मोत्सव कोन कोन सुन रहा ...,6.3K,3 days ago
1,आज 23 अप्रैल को हनुमान जी के पावन जनमोतसव पर क...,142,2 days ago
2,Aaj 26 April ( Friday ) jai shree ram jai ja...,50,3 hours ago (edited)
3,आज 26 तारीख कोन हनुमान चालीसा सुन रहा हे़ . जय...,67,13 hours ago
4,आज 26 अप्रैल.... आपका दिन मंगलमय हो... जय श्री...,319,2 days ago (edited)
...,...,...,...
1184,s s s,,5 hours ago
1185,🫶🇮🇳,,9 hours ago
1186,K̤d̤p̤d̤h̤o̤d̤h̤x̤o̤x̤h̤p̤x̤h̤x̤p̤x̤g̤k̤x̤g̤x̤...,,3 hours ago
1187,,,15 hours ago
1188,Jsjrjjriririir,,11 hours ago

# Ques 9:-

Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall
reviews, privates from price, dorms from price, facilities and property description.

In [11]:
driver=webdriver.Chrome()

In [12]:
driver.get('https://www.hostelworld.com')

In [13]:
driver.maximize_window()

In [14]:
location=driver.find_element(By.XPATH,'/html/body/div[3]/div/div[2]/main/header/div/div[2]/div[1]/div[1]/div/div[1]/div[1]/div/div[2]/input')
location.send_keys('London')

In [15]:
search=driver.find_element(By.XPATH,'/html/body/div[3]/div/div[2]/main/header/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/ul/li[2]/button/div[2]/div[1]')
search.click()

In [19]:
button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div[2]/main/header/div/div[2]/div[1]/div[1]/div/div[5]/button[1]')
button.click()

In [20]:
Hostel_urls=[]
url=driver.find_elements(By.XPATH,'//a[@class="nuxt-link"]')
for i in url:
    Hostel_urls.append(i.get_attribute("href"))
    time.sleep(2)

In [22]:
hostel_name=[]
distance=[]
rating=[]
total_review=[]
overall_review=[]
facility=[]
Property_description=[]
dorm_from_price=[]
private_from_price=[]

for url in Hostel_urls:
    driver.get(url)
    time.sleep(2)
    
    try:
        name=driver.find_element(By.XPATH,'//div[@class="title-2"]')
        hostel_name.append(name.text.replace("/n","new line"))
    except:
        hostel_name.append('-')
        
    try:
        dis=driver.find_element(By.XPATH,'//button[@class="property-address"]')
        distance.append(dis.text)
    except:
        distance.append('-')
        
    try:
        rate=driver.find_element(By.XPATH,'//div[@class="score orange big"]')
        rating.append(rate.text)
    except:
        rating.append('-')
        
    try:
        over=driver.find_element(By.XPATH,'//div[@class="keyword"]/span')
        overall_review.append(over.text)
    except:
        overall_review.append('-')
        
    try:
        total=driver.find_element(By.XPATH,'//div[@class="reviews"]')
        total_review.append(total.text)
    except:
        total_review.append('-')
        
    try:
        fac=driver.find_element(By.XPATH,'//ul[@class="facility-sections"]')
        facility.append(fac.text)
    except:
        facility.append('-')
        
    try:
        desc=driver.find_element(By.XPATH,'//div[@class="content collapse-content"]')
        Property_description.append(desc.text)
    except:
        Property_description.append('-')
     
    try:
        dorm=driver.find_element(By.XPATH,'//div[@class="rate-list"]')
        dorm_from_price.append(dorm.text)
    except:
        dorm_from_price.append('-')
        
    try:
        private=driver.find_element(By.XPATH,'//div[@class="rate-list"]')
        private_from_price.append(private.text)
    except:
        private_from_price.append('-')

In [23]:
df=pd.DataFrame({'hostel_name':hostel_name,'distance':distance,'rating':rating,'overall review':overall_review,'total review':total_review,'facilities':facility,'property description':Property_description,'dorm from price':dorm_from_price,'private from price':private_from_price})
df

,hostel_name,distance,rating,overall review,total review,facilities,property description,dorm from price,private from price
0,Palmers Lodge - Swiss Cottage,"40 College Crescent, Swiss Cottage,",8.7,Fabulous,16109 Total Reviews,Free\nLinen Included Free WiFi Free Internet A...,"Whether you're a backpacker, flash-packer or a...",-26%\n€39.74\n€53.70\nTax included\n\nStandard...,-26%\n€39.74\n€53.70\nTax included\n\nStandard...
1,St Christopher's Village,"165 Borough High Street,",7.6,Very Good,13008 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,St Christopher's Inn at The Village in London ...,-10%\n€30.79\n€34.21\nTax included\n\nStandard...,-10%\n€30.79\n€34.21\nTax included\n\nStandard...
2,Wombat's City Hostel London,"7 Dock Street,",9.2,Superb,16275 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,A safe haven in the middle of the metropolis: ...,-20%\n€411.32\n€514.16\nTax included\n\nStanda...,-20%\n€411.32\n€514.16\nTax included\n\nStanda...
3,Palmers Lodge - Swiss Cottage,"40 College Crescent, Swiss Cottage,",8.7,Fabulous,16109 Total Reviews,Free\nLinen Included Free WiFi Free Internet A...,"Whether you're a backpacker, flash-packer or a...",-26%\n€39.74\n€53.70\nTax included\n\nStandard...,-26%\n€39.74\n€53.70\nTax included\n\nStandard...
4,NX London Hostel,"323 New Cross Road,",8.8,Fabulous,2306 Total Reviews,Free\nFree Breakfast Linen Included Towels Inc...,Welcome to NX London Hostel!\n\nPLEASE READ IN...,-25%\n€174.64\n€232.86\nTax included\n\nNon-re...,-25%\n€174.64\n€232.86\nTax included\n\nNon-re...
5,Urbany Hostel London,"48-49 Princes Square, Paddington,",9.6,Superb,1209 Total Reviews,Free\nLinen Included Free WiFi\nGeneral\nSecur...,Welcome to Urbany Hostel London! Ideal for the...,€165.17\nTax included\n\nStandard\nChoose\n€14...,€165.17\nTax included\n\nStandard\nChoose\n€14...
6,Onefam Notting Hill,"63 Prince's Square,",9.7,Superb,2749 Total Reviews,Free\nLinen Included Free WiFi Free Internet A...,The perfect place for solo travelers to connec...,€222.95\nTax included\n\nStandard\nChoose\n€20...,€222.95\nTax included\n\nStandard\nChoose\n€20...
7,Onefam Waterloo,"73 Lambeth Walk, London,",9.6,Superb,276 Total Reviews,Free\nLinen Included Free WiFi Free Internet A...,Come join us at our newest Onefam location in ...,€239.94\nTax included\n\nStandard\nChoose\n€21...,€239.94\nTax included\n\nStandard\nChoose\n€21...
8,Generator London,"Compton Place, Off 37 Tavistock Place, WC1,",7.5,Very Good,8184 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Generator London is a design hotel-hostel loca...,-20%\n€42.87\n€53.59\nTax included\n\nStandard...,-20%\n€42.87\n€53.59\nTax included\n\nStandard...
9,St Christopher's Village,"165 Borough High Street,",7.6,Very Good,13008 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,St Christopher's Inn at The Village in London ...,-10%\n€30.79\n€34.21\nTax included\n\nStandard...,-10%\n€30.79\n€34.21\nTax included\n\nStandard...
10,Safestay London Elephant & Castle,"144-152 Walworth Road,",7.6,Very Good,5322 Total Reviews,Free\nLinen Included Free WiFi\nGeneral\nSecur...,Safestay at Elephant & Castle is ideal if you ...,€121.73\nTax included\n\nNon-refundable\nChoose,€121.73\nTax included\n\nNon-refundable\nChoose
11,Smart Russell Square Hostel,"71 Guilford Street,",7.5,Very Good,10258 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Poor noise insulation if your room is located ...,€42.56\nTax included\n\nStandard\nChoose\n€38....,€42.56\nTax included\n\nStandard\nChoose\n€38....
12,Astor Hyde Park,"191 Queensgate, South Kensington,",8.0,Fabulous,12378 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Located in the most beautiful and charming nei...,-10%\n€39.26\n€43.62\nTax included\n\nStandard...,-10%\n€39.26\n€43.62\nTax included\n\nStandard...
13,Astor Museum Inn,"27 Montague Street, Bloomsbury,",8.4,Fabulous,9493 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,With the British Museum literally on its doors...,-10%\n€42.70\n€47.45\nTax included\n\nStandard...,-10%\n€42.70\n€47.45\nTax included\n\nStandard...
14,Queen Elizabeth Chelsea,"58 Bagleys Lane,",7.7,Very Good,3760 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...,€27.15\nTax included\n\nStandard\nChoose\n€22....,€27.15\nTax included\n\nStandard\nChoose\n€22....
15,Safestay London Kensington Holland Park,"Holland Park Ave, Holland Walk,",7.2,Very Good,1846 Total Reviews,Free\nLinen Included Free WiFi\nGeneral\nSecur...,Safestay Holland Park\n\nSafestay Holland Park...,€26.48\nTax included\n\nNon-refundable\nChoose,€26.48\nTax included\n\nNon-refundable\nChoose
16,Phoenix Hostel,"6 Daventry Street,",6.9,Good,4696 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,"The Phoenix Bar & Hostel, housed in a homely E...",-5%\n€30.96\n€32.59\nTax included\n\nStandard\...,-5%\n€30.96\n€32.59\nTax included\n\nStandard\...
17,Hostelle - women only hostel London,"458 Bethnal Green road,",8.6,Fabulous,161 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Hostelle is the first and only all-women hoste...,-5%\n€56.39\n€59.36\nTax included\n\nStandard\...,-5%\n€56.39\n€59.36\nTax included\n\nStandard\...
18,Smart Hyde Park Inn Hostel,"48 - 50 Inverness Terrace, Bayswater,",7.8,Very Good,6833 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Rooms are great value because they got a curta...,€39.26\nTax included\n\nStandard\nChoose\n€35....,€39.26\nTax included\n\nStandard\nChoose\n€35....
19,St Christopher's Inn - London Bridge,"121 Borough High Street,",7.8,Very Good,3638 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Base yourself in the electric area of London B...,-10%\n€36.54\n€40.60\nTax included\n\nStandard...,-10%\n€36.54\n€40.60\nTax included\n\nStandard...
20,YHA London Central,"104-108 Bolsover St,",8.9,Fabulous,4814 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,YHA London Central boasts seven floors of mode...,€252.18\nTax included\n\nStandard\nChoose,€252.18\nTax included\n\nStandard\nChoose
21,Kabannas London St Pancras,"79-81 Euston Road,",8.3,Fabulous,3017 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,Located opposite Kings Cross/St Pancras Intern...,€71.00\nTax included\n\nStandard\nChoose,€71.00\nTax included\n\nStandard\nChoose
22,Barmy Badger Backpackers,"17 Longridge Road, Earls Court,",8.9,Fabulous,2058 Total Reviews,Free\nFree Breakfast Linen Included Free City ...,The Badger is unique for London in that we hav...,€122.41\nTax included\n\nStandard\nChoose,€122.41\nTax included\n\nStandard\nChoose
23,St Christopher's Hammersmith,"28, Hammersmith Broadway, Hammersmith,",7.7,Very Good,4440 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,This hostel is one of a kind. With Belushis re...,-10%\n€30.99\n€34.44\nTax included\n\nStandard...,-10%\n€30.99\n€34.44\nTax included\n\nStandard...
24,Astor Victoria,"73 Belgrave Road, Victoria,",7.3,Very Good,15132 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,With Victoria Station and Buckingham Palace a ...,-10%\n€35.30\n€39.22\nTax included\n\nStandard...,-10%\n€35.30\n€39.22\nTax included\n\nStandard...
25,Smart Camden Inn Hostel,"55/57 Bayham Street, Camden,",8.6,Fabulous,3171 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,The only thing that I would say was the commun...,€53.04\nTax included\n\nStandard\nChoose\n€47....,€53.04\nTax included\n\nStandard\nChoose\n€47....
26,Astor Kensington,"45 Queensborough Terrace, Bayswater,",8.1,Fabulous,6611 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,"Located a short walk from Notting Hill, Hyde P...",-10%\n€44.96\n€49.95\nTax included\n\nStandard...,-10%\n€44.96\n€49.95\nTax included\n\nStandard...
27,Bell House Hostel,"91 Bell St, Bell House,",7.1,Very Good,166 Total Reviews,Free\nLinen Included Free WiFi\nGeneral\nSecur...,"Boasting a bar and a shared lounge, Bell House...",€35.30\nTax included\n\nStandard\nChoose,€35.30\nTax included\n\nStandard\nChoose
28,Saint James Backpackers,"21 Longridge Road,",7.3,Very Good,1965 Total Reviews,Free\nFree Breakfast Linen Included Free City ...,We are located in central London - just 5 minu...,-,-
29,St Christopher's Camden,"48-50 Camden High Street, Camden NW1,",7.4,Very Good,4158 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,"Find our Camden hostel in London's north, smac...",-10%\n€30.99\n€34.44\nTax included\n\nStandard...,-10%\n€30.99\n€34.44\nTax included\n\nStandard...
30,St Christopher's Shepherds Bush,"Belushis Bar, 13-15 Shepherds Bush Green.,",7.8,Very Good,851 Total Reviews,Free\nLinen Included Free City Maps Free WiFi\...,St Christopher's Inn Shepherds Bush gives trav...,-10%\n€30.13\n€33.49\nTax included\n\nStandard...,-10%\n€30.13\n€33.49\nTax included\n\nStandard...
31,St Christopher's Greenwich,"189 Greenwich High Road, Greenwich,",8.0,Fabulous,3453 Total Reviews,Free\nLinen Included Free City Maps Free WiFi ...,Discover South London's rich history in the ci...,-10%\n€28.02\n€31.12\nTax included\n\nStandard...,-10%\n€28.02\n€31.12\nTax included\n\nStandard...