In [1]:
!pip install selenium

Requirement already satisfied: selenium in d:\users\kakug\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in d:\users\kakug\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in d:\users\kakug\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in d:\users\kakug\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in d:\users\kakug\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in d:\users\kakug\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in d:\users\kakug\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import pandas as pd
import selenium
import time
import requests
import regex as re
import warnings
warnings.filterwarnings("ignore")

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException

# Ques 1:-

Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A)
Rank
B) Name
C) Artist
D) Upload date
E) Views

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get(' https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos ')

In [5]:
driver.maximize_window()

In [6]:
rank=[]
name=[]
artist=[]
upload_date=[]
views=[]

In [7]:

try:
    video_name=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[1]')
    for i in video_name:
        name.append(i.text)
except:
    name.append('-')
    
    
try:
    name_of_artist=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')
    for i in name_of_artist:
        artist.append(i.text)
except:
    artist.append('-')
    
try:
    date=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')
    for i in date:
        upload_date.append(i.text)
except:
    upload_date.append('-')
    
try:
    view=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')
    for i in view:
        views.append(i.text)
except:
    views.append('-')
    
rank = [i for i in range(1, len(name) + 1)]

In [8]:
import pandas as pd
data = pd.DataFrame({
    'Rank': rank,
    'Name': name,
    'Artist': artist,
    'Upload Date': upload_date,
    'Views (Billions)': views
})

data

,Rank,Name,Artist,Upload Date,Views (Billions)
0,1,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.32
1,2,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.41
2,3,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.89
3,4,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.66
4,5,"""Shape of You""[20]",Ed Sheeran,"January 30, 2017",6.23
5,6,"""See You Again""[23]",Wiz Khalifa,"April 6, 2015",6.22
6,7,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.01
7,8,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.75
8,9,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.18
9,10,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.10
10,11,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.09
11,12,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.59
12,13,"""Masha and the Bear – Recipe for Disaster""[38]",Get Movies,"January 31, 2012",4.57
13,14,"""Axel F""[39]",Crazy Frog,"June 16, 2009",4.45
14,15,"""Sugar""[40]",Maroon 5,"January 14, 2015",4.02
15,16,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.01
16,17,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",4.00
17,18,"""Lakdi Ki Kathi""[43]",Jingle Toons,"June 14, 2018",3.98
18,19,"""Roar""[44]",Katy Perry,"September 5, 2013",3.98
19,20,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.89
20,21,"""Sorry""[46]",Justin Bieber,"October 22, 2015",3.78
21,22,"""Shree Hanuman Chalisa""[47]",T-Series Bhakti Sagar,"May 10, 2011",3.77
22,23,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.76
23,24,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.75
24,25,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.70
25,26,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.70
26,27,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.64
27,28,"""Faded""[53]",Alan Walker,"December 3, 2015",3.60
28,29,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.58
29,30,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.57

# Ques 2:-

Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [9]:
driver=webdriver.Chrome()

In [10]:
driver.get(' https://www.bcci.tv/')

In [11]:
driver.maximize_window()

In [12]:
fixture=driver.find_element(By.XPATH,'/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
fixture.click()

In [15]:
more=driver.find_element(By.XPATH,'/html/body/section/div/div/div/div/div/div[2]/div[2]/div[2]/div/button')
more.click()

In [16]:
series=[]
place=[]
date=[]
time=[]

In [17]:
try:
    Series=driver.find_elements(By.XPATH,'//div[@class="match-info"]/h5')
    for i in Series:
        series.append(i.text)
except:
    series.append('-')
    
try:
    Place=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
    for i in Place:
        place.append(i.text)
except:
    place.append('-')
    
try:
    Date=driver.find_elements(By.XPATH,'//div[@class="match-date-info"]/div[1]')
    for i in Date:
        date.append(i.text)
except:
    date.apend('-')
    
try:
    Time=driver.find_elements(By.XPATH,'//div[@class="match-date-info"]/div[2]')
    for i in Time:
        time.append(i.text)
except:
    time.append('-')

In [18]:
import pandas as pd
df=pd.DataFrame({'series':series,'place':place,'date':date,'time':time})
df

,series,place,date,time
0,INDIA WOMEN TOUR OF BANGLADESH T20 SERIES 2024,"Sylhet International Cricket Stadium, Sylhet","6 MAY, 2024",3:30 PM IST
1,INDIA WOMEN TOUR OF BANGLADESH T20 SERIES 2024,"Sylhet International Cricket Stadium, Sylhet","9 MAY, 2024",3:30 PM IST
2,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","5 JUNE, 2024",8:00 PM IST
3,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","9 JUNE, 2024",8:00 PM IST
4,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","12 JUNE, 2024",8:00 PM IST
5,ICC MENS T20 WORLD CUP 2024,"Central Broward Park & Broward County Stadium,...","15 JUNE, 2024",8:00 PM IST
6,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","6 JULY, 2024",8:00 PM IST
7,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","7 JULY, 2024",8:00 PM IST
8,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","10 JULY, 2024",8:00 PM IST
9,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","13 JULY, 2024",8:00 PM IST
10,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","14 JULY, 2024",8:00 PM IST

# Ques 3:-

Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get(' http://statisticstimes.com/')

In [5]:
driver.maximize_window()

In [6]:
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()

In [7]:
india=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()

In [8]:
GDP=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP.click()

In [9]:
rank=[]
state=[]
GSDP1=[]
GSDP2=[]
GSDP3=[]
share=[]
GDP=[]

In [10]:
try:
    Rank=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[1]')
    for i in Rank:
        rank.append(i.text)
except:
    rank.append('-')
    
try:
    State=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[2]')
    for i in State:
        state.append(i.text)
except:
    state.append('-')
        
try:
    gsdp1=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[3]')
    for i in gsdp1:
        GSDP1.append(i.text)
except:
    GSDP1.append('-')
    
try:
    gsdp2=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[4]')
    for i in gsdp2:
        GSDP2.append(i.text)
except:
    GSDP2.append('-')
    
try:
    gsdp3=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[5]')
    for i in gsdp3:
        GSDP3.append(i.text)
except:
    GSDP.append('-')
    

try:
    gdp=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[7]')
    for i in gdp:
        GDP.append(i.text)
except:
    GDP.append('-')

try:
    Share=driver.find_elements(By.XPATH,'//div[@class="fwidth"][3]/div/div/table/tbody/tr/td[6]')
    for i in Share:
        share.append(i.text)
except:
    share.append('-')

In [11]:
import pandas as pd
df=pd.DataFrame({'rank':rank,'state':state,'GSDP(23-24)':GSDP1,'GSDP(22-23)':GSDP2,'GSDP(21-22)':GSDP3,'share(21-22)':share,'GDP($billion)':GDP})
df

,rank,state,GSDP(23-24),GSDP(22-23),GSDP(21-22),share(21-22),GDP($billion)
0,1,Maharashtra,-,-,"3,108,022",13.17%,414.928
1,2,Tamil Nadu,"2,700,109","2,364,514","2,071,286",8.78%,276.522
2,3,Karnataka,"2,500,733","2,269,995","1,978,094",8.38%,264.080
3,4,Uttar Pradesh,"2,547,861","2,258,040","1,975,595",8.37%,263.747
4,5,Gujarat,-,"2,230,609","1,928,683",8.17%,257.484
5,6,West Bengal,"1,700,939","1,531,758","1,329,238",5.63%,177.456
6,7,Rajasthan,"1,524,030","1,365,849","1,193,489",5.06%,159.334
7,8,Andhra Pradesh,"1,439,674","1,303,524","1,148,471",4.87%,153.324
8,9,Telangana,"1,463,960","1,308,034","1,124,204",4.76%,150.084
9,10,Madhya Pradesh,"1,363,327","1,246,471","1,092,964",4.63%,145.913
10,11,Kerala,-,"1,046,188","934,542",3.96%,124.764
11,12,Delhi,"1,107,746","1,014,688","881,336",3.73%,117.660
12,13,Haryana,"1,095,535","984,055","868,905",3.68%,116.001
13,14,Odisha,"832,790","753,177","662,886",2.81%,88.497
14,15,Bihar,-,"751,396","650,302",2.76%,86.817
15,16,Punjab,"736,423","676,164","617,192",2.62%,82.397
16,17,Assam,"565,401","493,167","411,454",1.74%,54.930
17,18,Chhattisgarh,"505,887","464,399","410,525",1.74%,54.806
18,19,Jharkhand,-,"393,722","358,863",1.52%,47.909
19,20,Uttarakhand,"346,206","303,781","267,143",1.13%,35.664
20,21,Jammu & Kashmir,"246,465","224,226","193,352",0.82%,25.813
21,22,Himachal Pradesh,"207,430","191,728","172,162",0.73%,22.984
22,23,Goa,-,"93,672","84,266",0.36%,11.250
23,24,Tripura,-,"72,636","62,550",0.27%,8.351
24,25,Chandigarh,-,"54,285","46,096",0.20%,6.154
25,26,Puducherry,-,"49,643","43,810",0.19%,5.849
26,27,Meghalaya,"47,381","42,697","38,785",0.16%,5.178
27,28,Sikkim,-,"42,756","37,557",0.16%,5.014
28,29,Manipur,-,-,"36,594",0.16%,4.885
29,30,Arunachal Pradesh,-,"39,630","34,775",0.15%,4.643
30,31,Nagaland,-,"35,643","31,038",0.13%,4.144
31,32,Mizoram,-,-,"27,824",0.12%,3.715
32,33,Andaman & Nicobar Islands,-,-,"10,371",0.04%,1.385

# Question 4:-

Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used 
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [30]:
driver=webdriver.Chrome()

In [31]:
driver.get(' https://github.com/')

In [32]:
driver.maximize_window()

In [34]:
menu=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/button/span/span')
menu.click()

In [35]:
open_source=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
open_source.click()

In [36]:
trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [37]:
title=[]
description=[]
contributors=[]
languages=[]

In [41]:
try:
    Title=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a')
    for i in Title:
        title.append(i.text)
except:
    title.append('-')
    
try:
    desc=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in desc:
        description.append(i.text)
except:
    description.append('-')
    
    
try:
    cont=driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/a[1]') 
    for i in cont:
        contributors.append(i.text)
except:
    contributors.append('-')
    
    
try:
    lang=driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/span[1]')
    for i in lang:
        languages.append(i.text)
except:
    languages.append('-')

In [39]:
print(len(title)),print(len(description)),print(len(contributors)),print(len(languages))

25
24
25
25

(None, None, None, None)

In [42]:
df=pd.DataFrame({'title':title[:25],'description':description[:25],'contributors count':contributors[:25],'languages':languages[:25]})
df

,title,description,contributors count,languages
0,dnhkng / GlaDOS,Personality Core,"1,299",Python
1,TheOfficialFloW / PPPwn,PPPwn - PlayStation 4 PPPoE RCE,939,Python
2,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"389,177",TypeScript
3,fastfetch-cli / fastfetch,"Like neofetch, but much faster because written...","3,130",C
4,hydralauncher / hydra,Hydra is a game launcher with its own embedded...,"3,397",TypeScript
5,TracecatHQ / tracecat,😼 The open source alternative to Tines / Splun...,"1,682",TypeScript
6,coollabsio / coolify,An open-source & self-hostable Heroku / Netlif...,"14,833",PHP
7,dylanaraps / neofetch,🖼️ A command-line system information tool writ...,"20,722",Shell
8,ItzCrazyKns / Perplexica,Perplexica is an AI-powered search engine. It ...,"2,430",TypeScript
9,Orange-OpenSource / hurl,"Hurl, run and test HTTP requests with plain text.","11,201",Rust
10,pagefaultgames / pokerogue,Penpot: The open-source design tool for design...,851,TypeScript
11,penpot / penpot,💯 Curated coding interview preparation materia...,"27,797",Clojure
12,yangshun / tech-interview-handbook,"Open Source Alternative to Vercel, Netlify and...","110,733",TypeScript
13,Dokploy / dokploy,Master programming by recreating your favorite...,"1,387",TypeScript
14,codecrafters-io / build-your-own-x,OSWorld: Benchmarking Multimodal Agents for Op...,"258,846",Built by
15,xlang-ai / OSWorld,A visual no-code/code-free web crawler/spider易...,823,Python
16,NaiboWang / EasySpider,"A collection of inspiring lists, manuals, chea...","22,690",JavaScript
17,trimstray / the-book-of-secret-knowledge,"On-device AI across mobile, embedded and edge ...","130,524",Built by
18,pytorch / executorch,Bootstrap Kubernetes the hard way. No scripts.,"1,020",C++
19,kelseyhightower / kubernetes-the-hard-way,MagicMirror² is an open source modular smart m...,"38,896",Built by
20,MagicMirrorOrg / MagicMirror,Aptos is a layer 1 blockchain built to support...,"19,182",JavaScript
21,aptos-labs / aptos-core,Level up your Aviator game! This bot employs i...,"5,822",Rust
22,idk10-a / aviator,The FRRouting Protocol Suite,207,Built by
23,FRRouting / frr,The content behind MDN Web Docs,"3,035",C
24,mdn / content,Personality Core,"8,800",Markdown

# Question 5:-

Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [74]:
driver=webdriver.Chrome()

In [75]:
driver.get('https:/www.billboard.com/')

In [76]:
driver.maximize_window()

In [77]:
button=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button')
button.click()

In [78]:
charts=driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/h3/a')
charts.click()

In [79]:
hot=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a')
hot.click()

In [51]:
song_name=[]
artist_name=[]
last_week_rank=[]
peak_rank=[]
weeks_on_board=[]

In [68]:
try:
    name=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//ul/li/h3')
    for i in name:
        song_name.append(i.text)
except:
    song_name.append('-')
    
try:
    Name=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul[1]/li[1]/span')
    for i in Name:
        artist_name.append(i.text)
except:
    artist_name.append('-')
    
try:
    week=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[4]/span')
    for i in week:
        last_week_rank.append(i.text)
except:
    last_week_rank.append('-')
    
try:
    peak=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[5]/span')
    for i in peak:
        peak_rank.append(i.text)
except:
    peak_rank.append('-')
    
try:
    week=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[6]/span')
    for i in week:
        weeks_on_board.append(i.text)
except:
    weeks_on_board.append('-')

In [70]:
print(len(song_name))

7

In [71]:
Rank=[]
Song_Name=[]
Artist_Name=[]
Last_Week_Rank=[]
Peak_Rank=[]
Weeks_On_Board=[]

In [80]:
r=driver.find_elements(By.XPATH,'//span[@class="c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet"]')
for i in r:
    if i.text is None:
        Rank.append('-')
    else:
        Rank.append(i.text)
        
len(Rank),print(Rank)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']

(100, None)

In [81]:
sn=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//ul/li/h3')
for i in sn:
    if i.text is None:
        Song_Name.append('-')
    else:
        Song_Name.append(i.text)

len(Song_Name),print(Song_Name)

['Fortnight', 'Down Bad', 'I Can Do It With A Broken Heart', 'The Tortured Poets Department', 'So Long, London', 'My Boy Only Breaks His Favorite Toys', 'But Daddy I Love Him', 'Florida!!!', "Who's Afraid Of Little Old Me?", 'Guilty As Sin?', 'Fresh Out The Slammer', 'loml', 'The Alchemy', 'The Smallest Man Who Ever Lived', 'Beautiful Things', 'Too Sweet', 'Like That', 'Lose Control', 'Push Ups', 'I Can Fix Him (No Really I Can)', 'Clara Bow', 'Espresso', 'thanK you aIMee', 'So High School', 'The Black Dog', 'imgonnagetyouback', 'A Bar Song (Tipsy)', 'Lovin On Me', 'Saturn', 'The Albatross', "Texas Hold 'Em", 'The Prophecy', "We Can't Be Friends (Wait For Your Love)", 'I Hate It Here', 'How Did It End?', 'Chloe Or Sam Or Sophia Or Marcus', 'Stick Season', 'I Like The Way You Kiss Me', "I Look In People's Windows", 'I Remember Everything', 'Cruel Summer', 'Greedy', 'Type Shit', 'Cassandra', 'Agora Hills', 'Peter', 'The Bolter', 'Wanna Be', 'Get It Sexyy', 'Feather', 'The Manuscript', 'Carnival', 'FTCU', 'Whatever She Wants', 'Robin', 'End Of Beginning', 'Redrum', 'Gata Only', 'Yeah Glo!', 'Austin', 'Never Lose Me', 'Good Luck, Babe!', 'Act II: Date @ 8', 'Made For Me', 'Where It Ends', 'Tell Ur Girlfriend', 'FE!N', 'Wild Ones', 'Slow It Down', 'Cinderella', 'Wildflowers And Wild Horses', 'Hell N Back', 'Back Then Right Now', 'Obsessed', 'Get In With Me', "Wind Up Missin' You", 'Mmhmm', 'Illusion', 'Bulletproof', 'Enough (Miami)', 'Everybody', 'Scared To Start', 'La Diabla', 'II Most Wanted', 'Cry', 'Outskirts', 'Tu Name', "We Still Don't Trust You", 'One Of The Girls', "Let's Go", '23', 'Tucson Too Late', 'Halfway To Hell', 'Praise Jah In The Moonlight', 'Feel It', 'Us Vs. Them', 'Wine Into Whiskey', 'Spin You Around (1/24)', 'Soak City', 'Selfish']

(100, None)

In [82]:
an=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul[1]/li[1]/span')
for i in an:
    if i.text is None:
        Artist_Name.append('-')
    else:
        Artist_Name.append(i.text)
        
len(Artist_Name),print(Artist_Name)

['Taylor Swift Featuring Post Malone', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift Featuring Florence + The Machine', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Benson Boone', 'Hozier', 'Future, Metro Boomin & Kendrick Lamar', 'Teddy Swims', 'Drake', 'Taylor Swift', 'Taylor Swift', 'Sabrina Carpenter', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Shaboozey', 'Jack Harlow', 'SZA', 'Taylor Swift', 'Beyonce', 'Taylor Swift', 'Ariana Grande', 'Taylor Swift', 'Taylor Swift', 'Taylor Swift', 'Noah Kahan', 'Artemas', 'Taylor Swift', 'Zach Bryan Featuring Kacey Musgraves', 'Taylor Swift', 'Tate McRae', 'Future, Metro Boomin, Travis Scott & Playboi Carti', 'Taylor Swift', 'Doja Cat', 'Taylor Swift', 'Taylor Swift', 'GloRilla & Megan Thee Stallion', 'Sexyy Red', 'Sabrina Carpenter', 'Taylor Swift', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', 'Nicki Minaj', 'Bryson Tiller', 'Taylor Swift', 'Djo', '21 Savage', 'FloyyMenor X Cris Mj', 'GloRilla', 'Dasha', 'Flo Milli', 'Chappell Roan', '4Batz Featuring Drake', 'Muni Long', 'Bailey Zimmerman', 'Lay Bankz', 'Travis Scott Featuring Playboi Carti', 'Jessie Murph & Jelly Roll', 'Benson Boone', 'Future, Metro Boomin & Travis Scott', 'Lainey Wilson', 'Bakar Featuring Summer Walker', 'Tyler Hubbard', 'Olivia Rodrigo', 'BossMan Dlow', 'Tucker Wetmore', 'BigXthaPlug', 'Dua Lipa', 'Nate Smith', 'Cardi B', 'Nicki Minaj Featuring Lil Uzi Vert', 'Michael Marcagi', 'Xavi', 'Beyonce & Miley Cyrus', 'Benson Boone', 'Sam Hunt', 'Fuerza Regida', 'Future, Metro Boomin & The Weeknd', 'The Weeknd, Jennie & Lily Rose Depp', 'Key Glock & Young Dolph', 'Chayce Beckham', 'Jordan Davis', 'Jelly Roll', 'YG Marley', 'd4vd', '$uicideBoy$', 'Tucker Wetmore', 'Morgan Wallen', '310babii', 'Justin Timberlake']

(100, None)

In [83]:
lw=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[4]/span')
for i in lw:
    if i.text is None:
        Last_Week_Rank.append('-')
    else:
        Last_Week_Rank.append(i.text)
        
len(Last_Week_Rank),print(Last_Week_Rank)

['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '3', '1', '2', '4', '-', '-', '-', '7', '-', '-', '-', '-', '36', '6', '10', '-', '5', '-', '8', '-', '-', '-', '9', '12', '-', '11', '13', '16', '14', '-', '15', '-', '-', '17', '23', '21', '-', '20', '80', '31', '-', '24', '25', '27', '32', '28', '33', '44', '30', '35', '38', '58', '45', '46', '49', '37', '50', '53', '62', '42', '52', '75', '63', '43', '64', '55', '65', '56', '57', '47', '69', '66', '68', '22', '70', '59', '74', '83', '85', '76', '94', '-', '84', '89', '82', '60']

(100, None)

In [84]:
pr=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[5]/span')
for i in pr:
    if i.text is None:
        Peak_Rank.append('-')
    else:
        Peak_Rank.append(i.text)
        
len(Peak_Rank),print(Peak_Rank)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '2', '1', '1', '1', '19', '20', '21', '7', '23', '24', '25', '26', '27', '1', '6', '30', '1', '32', '1', '34', '35', '36', '9', '12', '39', '1', '1', '3', '2', '44', '7', '46', '47', '11', '20', '21', '51', '1', '15', '19', '55', '11', '5', '27', '32', '28', '15', '44', '7', '20', '32', '58', '5', '35', '40', '6', '48', '53', '62', '14', '49', '75', '63', '43', '64', '9', '24', '54', '20', '6', '60', '66', '66', '22', '51', '59', '45', '80', '84', '34', '94', '96', '77', '24', '53', '19']

(100, None)

In [85]:
wb=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//ul[1]/li[4]/ul/li[6]/span')
for i in wb:
    if i.text is None:
        Weeks_On_Board.append('-')
    else:
        Weeks_On_Board.append(i.text)
        
len(Weeks_On_Board),print(Weeks_On_Board)

['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '14', '5', '5', '37', '1', '1', '1', '2', '1', '1', '1', '1', '2', '24', '9', '1', '11', '1', '7', '1', '1', '1', '30', '5', '1', '35', '51', '32', '5', '1', '31', '1', '1', '3', '6', '21', '1', '11', '20', '10', '1', '10', '15', '6', '11', '7', '19', '3', '16', '15', '17', '2', '25', '29', '5', '5', '13', '3', '6', '5', '12', '4', '18', '2', '3', '6', '20', '10', '19', '4', '3', '7', '10', '2', '18', '7', '17', '8', '3', '13', '2', '1', '5', '13', '19', '13']

(100, None)

In [86]:
df1=pd.DataFrame({'Rank':Rank,'Song_Name':Song_Name,'Artist_Name':Artist_Name,'Last_Week_Rank':Last_Week_Rank,'Peak_Rank':Peak_Rank,'Weeks_On_Board':Weeks_On_Board})
df1

,Rank,Song_Name,Artist_Name,Last_Week_Rank,Peak_Rank,Weeks_On_Board
0,1,Fortnight,Taylor Swift Featuring Post Malone,-,1,1
1,2,Down Bad,Taylor Swift,-,2,1
2,3,I Can Do It With A Broken Heart,Taylor Swift,-,3,1
3,4,The Tortured Poets Department,Taylor Swift,-,4,1
4,5,"So Long, London",Taylor Swift,-,5,1
...,...,...,...,...,...,...
95,96,Us Vs. Them,$uicideBoy$,-,96,1
96,97,Wine Into Whiskey,Tucker Wetmore,84,77,5
97,98,Spin You Around (1/24),Morgan Wallen,89,24,13
98,99,Soak City,310babii,82,53,19
99,100,Selfish,Justin Timberlake,60,19,13

# Question 6:-

Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [87]:
driver=webdriver.Chrome()

In [88]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [89]:
driver.maximize_window()

In [90]:

book_name=[]
author_name=[]
volume_sold=[]
publisher=[]
genre=[]

In [96]:
book=driver.find_elements(By.XPATH,'//div[@class="embed block"]//table/tbody/tr/td[2]')
for i in book:
    book_name.append(i.text)
print(book_name),len(book_name)

['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

(None, 100)

In [97]:
author=driver.find_elements(By.XPATH,'//div[@class="embed block"]//table/tbody/tr/td[3]')
for i in author:
    author_name.append(i.text)
print(author_name),len(author_name)

['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']

(None, 100)

In [98]:
volume=driver.find_elements(By.XPATH,'//div[@class="embed block"]//table/tbody/tr/td[4]')
for i in volume:
    volume_sold.append(i.text)
print(volume_sold),len(volume_sold)

['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']

(None, 100)

In [99]:
pub=driver.find_elements(By.XPATH,'//div[@class="embed block"]//table/tbody/tr/td[5]')
for i in pub:
    publisher.append(i.text)
print(publisher),len(publisher)

['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']

(None, 100)

In [100]:
gen=driver.find_elements(By.XPATH,'//div[@class="embed block"]//table/tbody/tr/td[6]')
for i in gen:
    genre.append(i.text)
print(genre),len(genre)

['Crime, Thriller & Adventure', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Romance & Sagas', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Crime, Thriller & Adventure', "Children's Fiction", 'Romance & Sagas', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Romance & Sagas', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Popular Science', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Picture Books', 'Picture Books', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Humour: Collections & General', 'General & Literary Fiction', 'Autobiography: General', 'General & Literary Fiction', 'Biography: The Arts', 'Autobiography: General', 'Picture Books', 'Autobiography: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Science Fiction & Fantasy', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'Fitness & Diet', 'General & Literary Fiction', "Children's Fiction", 'Crime, Thriller & Adventure', 'Fitness & Diet', 'Young Adult Fiction', 'Usage & Writing Guides', 'Food & Drink: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Popular Culture & Media: General Interest', 'Autobiography: The Arts', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Science Fiction & Fantasy', 'Current Affairs & Issues', 'Crime, Thriller & Adventure', 'Autobiography: The Arts', 'General & Literary Fiction', 'Autobiography: The Arts', 'Travel Writing', 'Food & Drink: General', 'General & Literary Fiction', 'National & Regional Cuisine', 'Fitness & Diet', 'Travel Writing', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'Picture Books', 'General & Literary Fiction', 'Autobiography: The Arts', 'Popular Science', "Children's Annuals", 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Food & Drink: General', 'Young Adult Fiction', 'Biography: General', 'Food & Drink: General']

(None, 100)

In [101]:
df=pd.DataFrame({'book name':book_name,'author name':author_name,'volume sold':volume_sold,'publisher':publisher,'genre':genre})
df

,book name,author name,volume sold,publisher,genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Question 7:-

Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls512407256/ You have
to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [3]:
driver=webdriver.Chrome()
driver.get('https://www.imdb.com/list/ls512407256/')
driver.maximize_window()

In [4]:
name=[]
Year_span=[]
genre=[]
run_time=[]
ratings=[]
votes=[]

In [5]:
names=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
for i in names:
    name.append(i.text)
len(name),print(name)

['Game of Thrones', 'Stranger Things', 'The Walking Dead', '13 Reasons Why', 'The 100', 'Orange Is the New Black', 'Riverdale', "Grey's Anatomy", 'The Flash', 'Arrow', 'Money Heist', 'The Big Bang Theory', 'Black Mirror', 'Sherlock', 'Vikings', 'Pretty Little Liars', 'The Vampire Diaries', 'American Horror Story', 'Breaking Bad', 'Lucifer', 'Supernatural', 'Prison Break', 'How to Get Away with Murder', 'Teen Wolf', 'The Simpsons', 'Once Upon a Time', 'Narcos', 'Daredevil', 'Friends', 'How I Met Your Mother', 'Suits', 'Mr. Robot', 'The Originals', 'Supergirl', 'Gossip Girl', 'Sense8', 'Gotham', 'Westworld', 'Jessica Jones', 'Modern Family', 'Rick and Morty', 'Shadowhunters: The Mortal Instruments', 'The End of the F***ing World', 'House of Cards', 'Dark', 'Elite', 'Sex Education', 'Shameless', 'New Girl', 'Agents of S.H.I.E.L.D.', 'Game of Thrones', 'You', 'Stranger Things', 'Dexter', 'The Walking Dead', 'Fear the Walking Dead', '13 Reasons Why', 'Family Guy', 'The 100', 'The Blacklist', 'Orange Is the New Black', 'Lost', 'Riverdale', 'Peaky Blinders', "Grey's Anatomy", 'House M.D.', 'The Flash', 'Quantico', 'Arrow', 'Orphan Black', 'Money Heist', 'Homeland', 'The Big Bang Theory', 'Blindspot', 'Black Mirror', 'Legends of Tomorrow', 'Sherlock', "The Handmaid's Tale", 'Vikings', 'Chilling Adventures of Sabrina', 'Pretty Little Liars', 'The Good Doctor', 'The Vampire Diaries', 'Jane the Virgin', 'American Horror Story', 'Glee', 'Breaking Bad', 'South Park', 'Lucifer', 'Brooklyn Nine-Nine', 'Supernatural', 'Under the Dome', 'Prison Break', 'The Umbrella Academy', 'How to Get Away with Murder', 'True Detective', 'Teen Wolf', 'The OA', 'The Simpsons', 'Desperate Housewives']

(100, None)

In [6]:
year=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
for i in year:
    Year_span.append(i.text)
print(Year_span),len(Year_span)

['(2011–2019)', '(2016–2025)', '(2010–2022)', '(2017–2020)', '(2014–2020)', '(2013–2019)', '(2017–2023)', '(2005– )', '(2014–2023)', '(2012–2020)', '(2017–2021)', '(2007–2019)', '(2011– )', '(2010–2017)', '(2013–2020)', '(2010–2017)', '(2009–2017)', '(2011– )', '(2008–2013)', '(2016–2021)', '(2005–2020)', '(2005–2017)', '(2014–2020)', '(2011–2017)', '(1989– )', '(2011–2018)', '(2015–2017)', '(2015–2018)', '(1994–2004)', '(2005–2014)', '(2011–2019)', '(2015–2019)', '(2013–2018)', '(2015–2021)', '(2007–2012)', '(2015–2018)', '(2014–2019)', '(2016–2022)', '(2015–2019)', '(2009–2020)', '(2013– )', '(2016–2019)', '(2017–2019)', '(2013–2018)', '(2017–2020)', '(2018–2024)', '(2019–2023)', '(2011–2021)', '(2011–2018)', '(2013–2020)', '(2011–2019)', '(2018–2024)', '(2016–2025)', '(2006–2013)', '(2010–2022)', '(2015–2023)', '(2017–2020)', '(1999– )', '(2014–2020)', '(2013–2023)', '(2013–2019)', '(2004–2010)', '(2017–2023)', '(2013–2022)', '(2005– )', '(2004–2012)', '(2014–2023)', '(2015–2018)', '(2012–2020)', '(2013–2017)', '(2017–2021)', '(2011–2020)', '(2007–2019)', '(2015–2020)', '(2011– )', '(2016–2022)', '(2010–2017)', '(2017– )', '(2013–2020)', '(2018–2020)', '(2010–2017)', '(2017–2024)', '(2009–2017)', '(2014–2019)', '(2011– )', '(2009–2015)', '(2008–2013)', '(1997– )', '(2016–2021)', '(2013–2021)', '(2005–2020)', '(2013–2015)', '(2005–2017)', '(2019–2024)', '(2014–2020)', '(2014– )', '(2011–2017)', '(2016–2019)', '(1989– )', '(2004–2012)']

(None, 100)

In [7]:
gen=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')
for i in gen:
    genre.append(i.text)
print(genre),len(genre)

['Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Horror, Thriller', 'Drama, Mystery, Thriller', 'Drama, Mystery, Sci-Fi', 'Comedy, Crime, Drama', 'Crime, Drama, Mystery', 'Drama, Romance', 'Action, Adventure, Drama', 'Action, Adventure, Crime', 'Action, Crime, Drama', 'Comedy, Romance', 'Drama, Mystery, Sci-Fi', 'Crime, Drama, Mystery', 'Action, Adventure, Drama', 'Drama, Mystery, Romance', 'Drama, Fantasy, Horror', 'Drama, Horror, Sci-Fi', 'Crime, Drama, Thriller', 'Crime, Drama, Fantasy', 'Drama, Fantasy, Horror', 'Action, Crime, Drama', 'Crime, Drama, Mystery', 'Action, Drama, Fantasy', 'Animation, Comedy', 'Adventure, Fantasy, Romance', 'Biography, Crime, Drama', 'Action, Crime, Drama', 'Comedy, Romance', 'Comedy, Drama, Romance', 'Comedy, Drama', 'Crime, Drama, Thriller', 'Drama, Fantasy, Horror', 'Action, Adventure, Drama', 'Drama, Romance', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Comedy, Drama, Romance', 'Animation, Adventure, Comedy', 'Action, Drama, Fantasy', 'Adventure, Comedy, Crime', 'Drama', 'Crime, Drama, Mystery', 'Crime, Drama, Thriller', 'Comedy, Drama, Romance', 'Comedy, Drama', 'Comedy, Romance', 'Action, Adventure, Drama', 'Action, Adventure, Drama', 'Crime, Drama, Romance', 'Drama, Fantasy, Horror', 'Crime, Drama, Mystery', 'Drama, Horror, Thriller', 'Drama, Horror, Sci-Fi', 'Drama, Mystery, Thriller', 'Animation, Comedy', 'Drama, Mystery, Sci-Fi', 'Crime, Drama, Mystery', 'Comedy, Crime, Drama', 'Adventure, Drama, Fantasy', 'Crime, Drama, Mystery', 'Crime, Drama', 'Drama, Romance', 'Drama, Mystery', 'Action, Adventure, Drama', 'Crime, Drama, Mystery', 'Action, Adventure, Crime', 'Drama, Sci-Fi, Thriller', 'Action, Crime, Drama', 'Crime, Drama, Mystery', 'Comedy, Romance', 'Action, Crime, Drama', 'Drama, Mystery, Sci-Fi', 'Action, Adventure, Drama', 'Crime, Drama, Mystery', 'Drama, Sci-Fi, Thriller', 'Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Mystery, Romance', 'Drama', 'Drama, Fantasy, Horror', 'Comedy', 'Drama, Horror, Sci-Fi', 'Comedy, Drama, Music', 'Crime, Drama, Thriller', 'Animation, Comedy', 'Crime, Drama, Fantasy', 'Comedy, Crime', 'Drama, Fantasy, Horror', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Action, Adventure, Comedy', 'Crime, Drama, Mystery', 'Crime, Drama, Mystery', 'Action, Drama, Fantasy', 'Drama, Fantasy, Mystery', 'Animation, Comedy', 'Comedy, Drama, Mystery']

(None, 100)

In [8]:
run=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
for i in run:
    run_time.append(i.text)
    
print(run_time),len(run_time)

['60 min', '60 min', '45 min', '60 min', '43 min', '59 min', '45 min', '41 min', '43 min', '42 min', '60 min', '22 min', '60 min', '90 min', '45 min', '44 min', '43 min', '60 min', '45 min', '4,393 min', '44 min', '44 min', '43 min', '41 min', '22 min', '60 min', '50 min', '60 min', '22 min', '4,576 min', '44 min', '45 min', '45 min', '43 min', '42 min', '60 min', '42 min', '60 min', '56 min', '22 min', '23 min', '42 min', '25 min', '50 min', '60 min', '60 min', '60 min', '60 min', '22 min', '45 min', '60 min', '45 min', '60 min', '60 min', '45 min', '44 min', '60 min', '22 min', '43 min', '43 min', '59 min', '5,445 min', '45 min', '60 min', '41 min', '45 min', '43 min', '42 min', '42 min', '44 min', '60 min', '60 min', '22 min', '42 min', '60 min', '42 min', '90 min', '60 min', '45 min', '60 min', '44 min', '41 min', '43 min', '60 min', '60 min', '44 min', '45 min', '22 min', '4,393 min', '22 min', '44 min', '1,668 min', '44 min', '60 min', '43 min', '60 min', '41 min', '60 min', '22 min', '45 min']

(None, 100)

In [9]:
rate=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div[1]/span[2]')
for i in rate:
    ratings.append(i.text)
print(ratings),len(ratings)

['9.2', '8.7', '8.1', '7.5', '7.6', '8', '6.5', '7.6', '7.5', '7.5', '8.2', '8.1', '8.7', '9.1', '8.5', '7.4', '7.7', '8', '9.5', '8.1', '8.4', '8.3', '8.1', '7.7', '8.7', '7.7', '8.8', '8.6', '8.9', '8.3', '8.4', '8.5', '8.3', '6.2', '7.5', '8.2', '7.8', '8.5', '7.9', '8.5', '9.1', '6.5', '8', '8.6', '8.7', '7.2', '8.3', '8.5', '7.8', '7.5', '9.2', '7.7', '8.7', '8.6', '8.1', '6.8', '7.5', '8.1', '7.6', '7.9', '8', '8.3', '6.5', '8.8', '7.6', '8.7', '7.5', '6.7', '7.5', '8.3', '8.2', '8.3', '8.1', '7.3', '8.7', '6.8', '9.1', '8.4', '8.5', '7.4', '7.4', '8', '7.7', '7.9', '8', '6.8', '9.5', '8.7', '8.1', '8.4', '8.4', '6.5', '8.3', '7.9', '8.1', '8.9', '7.7', '7.8', '8.7', '7.6']

(None, 100)

In [10]:
vote=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]')
for i in vote:
    votes.append(i.text)
print(votes),len(votes)

['2,286,517', '1,337,576', '1,082,895', '315,665', '276,307', '320,286', '155,242', '342,052', '368,341', '446,145', '532,564', '868,596', '640,545', '999,437', '583,375', '178,426', '350,003', '344,159', '2,138,607', '356,239', '483,473', '579,755', '166,778', '163,344', '436,152', '237,131', '470,670', '475,008', '1,088,811', '728,832', '479,321', '418,511', '147,940', '129,608', '193,494', '163,091', '240,812', '533,175', '226,844', '483,992', '602,055', '70,599', '220,243', '531,085', '444,743', '90,836', '351,694', '285,745', '245,647', '226,039', '2,286,517', '300,048', '1,337,576', '767,188', '1,082,895', '144,437', '315,665', '364,479', '276,307', '279,771', '320,286', '595,628', '155,242', '650,480', '342,052', '514,083', '368,341', '63,902', '446,145', '117,013', '532,564', '361,052', '868,596', '79,074', '640,545', '110,076', '999,437', '258,159', '583,375', '108,600', '178,426', '113,161', '350,003', '59,088', '344,159', '155,503', '2,138,607', '406,136', '356,239', '363,722', '483,473', '112,580', '579,755', '275,513', '166,778', '657,028', '163,344', '115,936', '436,152', '139,841']

(None, 100)

In [11]:
import pandas as pd
df3=pd.DataFrame({'name':name,'year span':Year_span,'genre':genre,'run time':run_time,'ratings':ratings,'votes':votes})
df3

,name,year span,genre,run time,ratings,votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",60 min,9.2,"2,286,517"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",60 min,8.7,"1,337,576"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",45 min,8.1,"1,082,895"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"315,665"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"276,307"
...,...,...,...,...,...,...
95,True Detective,(2014– ),"Crime, Drama, Mystery",60 min,8.9,"657,028"
96,Teen Wolf,(2011–2017),"Action, Drama, Fantasy",41 min,7.7,"163,344"
97,The OA,(2016–2019),"Drama, Fantasy, Mystery",60 min,7.8,"115,936"
98,The Simpsons,(1989– ),"Animation, Comedy",22 min,8.7,"436,152"
99,Desperate Housewives,(2004–2012),"Comedy, Drama, Mystery",45 min,7.6,"139,841"

# Question 8:-

Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
 Note: - from the home page you have to go to the Show All Dataset page through code.

In [29]:
driver=webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')
driver.maximize_window()

In [30]:
try:
    click=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
    click.click()
    
except:
    print('no cookies available')

In [31]:
try:
    time.sleep(3)
    more=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]')
    more.click()
    
except:
    print('no cookies available')

In [33]:
pages=[]
start=0
end=66

for page in range(start,end):
    page=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in page:
        pages.append(i.get_attribute('href'))
    next_page=driver.find_element(By.XPATH,'//button[@class="btn-primary btn-sm btn"][2]')
    next_page.click()
    time.sleep(2)
len(pages)

660

In [34]:
Dataset =[]
Data_Type =[]
Task =[]
Attribute_Type =[]
No_of_Instances =[]
No_of_Attribute =[]
Year =[]

for i in pages:
    driver.get(i)
    time.sleep(2)

    try:
        dataset=driver.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        Dataset.append(dataset.text)
    except:
        Dataset.append('-')
        
    
    try:
        datatype=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[1]/p')
        Data_Type.append(datatype.text)
    except:
        Data_Type.append('-')
        

    try:
        task=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[3]/p')
        Task.append(task.text)
    except:
        Task.append('-')
        
        
    try:
        attributetype=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[4]/p')
        Attribute_Type.append(attributetype.text)
    except:
        Attribute_Type.append('-')
        

        
    try:
        no_of_instances=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[5]/p')
        No_of_Instances.append(no_of_instances.text)
    except:
        No_of_Instances.append('-')
        
        
    try:
        no_of_attribute=driver.find_element(By.XPATH,'//div[@class="grid grid-cols-8 gap-4 md:grid-cols-12"]/div[6]/p')
        No_of_Attribute.append(no_of_attribute.text)
    except:
        No_of_Attribute.append('-')
        
        

    try:
        year=driver.find_element(By.XPATH,'//h2[@class="text-sm text-primary-content"]')
        Year.append(year.text.split()[2])
    except:
        Year.append('-')
        
        
        
        
len(Dataset),len(Data_Type),len(Task),len(Attribute_Type),len(No_of_Instances),len(No_of_Attribute),len(Year)

(660, 660, 660, 660, 660, 660, 660)

In [35]:
df=pd.DataFrame({'DataSet Title':Dataset,'Data Type':Data_Type,'Task':Task,'Attribute Type':Attribute_Type,
                'No of Instances':No_of_Instances,
                'No of Attribute':No_of_Attribute,
                'Year':Year})
df

,DataSet Title,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Iris,Tabular,Classification,Real,150,4,6/30/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,13,6/30/1988
2,Dry Bean,Multivariate,Classification,"Integer, Real",13611,16,9/13/2020
3,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3810,7,10/5/2019
4,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,4/30/1996
...,...,...,...,...,...,...,...
655,BAUM-2,Time-Series,Classification,-,1047,-,11/8/2018
656,Prodigy,Domain-Theory,-,-,-,-,-
657,Undocumented,-,-,-,-,-,-
658,NSF Research Award Abstracts 1990-2003,Text,-,-,129000,-,11/17/2003
659,Moral Reasoner,Domain-Theory,-,-,202,-,5/31/1994